### ISSUE TITLE
[BUG] Weirdly positioned YouTube Music miniplayer

### ISSUE THREAD

**Issue by Khemanshu-S** [sameerasw/my-internet#1603]
## Describe the bug

The miniplayer on YouTube Music is positioned slightly off centered which just doesn't look right, it should be either in the bottom right corner or just not there at all since there is already a bar to control it on the bottom

## Steps to reproduce

1.Play a song on youtube music
2.Go to the homepage

## Expected behavior

Correctly positioned at the bottom right corner or not there

## Actual behavior

<img width="1878" height="998" alt="Image" src="https://github.com/user-attachments/assets/99808982-d596-453d-9d12-72ec09c1eace" />

## ZenInternet Settings Data
*This data was automatically collected to help with debugging.*

<details>
<summary>Click to expand settings data</summary>

```json
{
  "reportDate": "2025-07-23T12:50:55.373Z",
  "addonVersion": "2.6.2",
  "currentTabUrl": "https://music.youtube.com/playlist?list=OLAK5uy_kcaRWdKExi6Op8xtUMc_3h42ADIssBfdA",
  "currentTabHostname": "music.youtube.com",
  "browserInfo": {
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Firefox/140.0",
    "platform": "Linux x86_64"
  },
  "settings": {
    "globalSettings": {
      "enableStyling": true,
      "autoUpdate": true,
      "forceStyling": true,
      "whitelistMode": false,
      "whitelistStyleMode": false,
      "disableTransparency": false,
      "disableHover": false,
      "disableFooter": false,
      "fallbackBackgroundList": [],
      "lastFetchedTime": 1753037262546,
      "welcomeShown": true
    },
    "skipForceList": [],
    "skipThemingList": [],
    "fallbackBackgroundList": [],
    "currentSiteSettings": {
      "transparency": true,
      "Hover": false,
      "Hide elements": true,
      "Player sidebar": true,
      "Centered player": true,
      "Nav background removal": true,
      "Player bar styling": true,
      "Mini player tweaks": false,
      "Show mini playyer": false,
      "Immersive player": true,
      "Centered player bar": true,
      "Addon : timed comments pop-up": true
    }
  }
}
```

</details>

## Browser Information
- **Zen Browser Version:** Mozilla Zen 1.14.5b
- **Platform:** Linux x86_64
- **Extension Version:** 2.6.2

## Website
Current website: https://music.youtube.com/playlist?list=OLAK5uy_kcaRWdKExi6Op8xtUMc_3h42ADIssBfdA

**Comment by sameerasw** [comment]
Hi, Can you test now, I modified it but it seems like even tho it works fine for most, some users still get a different layout for a reason that I haven't yet found out.

**Comment by sameerasw** [comment]
Done, Theme added/ updated. Please re-fetch your styles in a short while :) 

<img width="742" height="1230" alt="Image" src="https://github.com/user-attachments/assets/e1e4c40d-c7b5-4de3-bfe2-3c7d7be2bc2b" />

[![Build Status](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Factions-badge.atrox.dev%2Fsameerasw%2Fmy-internet%2Fbadge%3Fref%3Dmain&style=for-the-badge)](https://actions-badge.atrox.dev/sameerasw/my-internet/goto?ref=main)

**Comment by Khemanshu-S** [comment]
its still the same 

<img width="1896" height="1010" alt="Image" src="https://github.com/user-attachments/assets/26a4306a-75a5-4706-9245-6724c90ea632" />

**Comment by sameerasw** [comment]
Are you using any other addons that can affect YT music by any chance? Because no matter how hard I try, I can not replicate this ;(

![Image](https://github.com/user-attachments/assets/df2cc557-87be-4b82-86ab-7298bf4c78ce)
