### ISSUE TITLE
[THEME] education.github.com

### ISSUE THREAD

**Issue by bhupesh98** [sameerasw/my-internet#810]
Please add a theme for education.github.com

**Comment by sameerasw** [comment]
This redirects me to just github, Maybe because I already got student?

> Please add a theme for education.github.com

**Comment by bhupesh98** [comment]
> This redirects me to just github, Maybe because I already got student?
> 
> > Please add a theme for education.github.com
> 
> 

Check this link: https://education.github.com/pack
Maybe a small tweak on the text should work. This problem is also on https://classroom.google.com

**Comment by sameerasw** [comment]
You will have to use darkreader to fix text color.

Done, re-fetch your styles in a short while :) 

<img width="377" alt="CleanShot 2025-03-08 at 10  02 30@2x" src="https://github.com/user-attachments/assets/fe3cefb1-e38c-4d2f-91df-4d6fdba3b804" />

[![Build Status](https://img.shields.io/endpoint.svg?url=https%3A%2F%2Factions-badge.atrox.dev%2Fsameerasw%2Fmy-internet%2Fbadge%3Fref%3Dmain&style=for-the-badge)](https://actions-badge.atrox.dev/sameerasw/my-internet/goto?ref=main)

**Comment by bhupesh98** [comment]
Strange, I thought the same and tried to turn on darkreader, but it doesn't fix. Github education is the least I'm bothered about. StackOverflow and Google classroom is what bothers me the most.

**Comment by sameerasw** [comment]
> Strange, I thought the same and tried to turn on darkreader, but it doesn't fix. Github education is the least I'm bothered about. StackOverflow and Google classroom is what bothers me the most.

Stackoverflow with darkreader:
<img width="1320" alt="Image" src="https://github.com/user-attachments/assets/8965a616-2585-4e30-bbb4-ffbb4a268f82" />

classroom (i got no content):
<img width="1324" alt="Image" src="https://github.com/user-attachments/assets/20f7c2a9-86cc-4bff-9a47-c075968db969" />

github education benefits:
<img width="1318" alt="Image" src="https://github.com/user-attachments/assets/ebf4cc83-e18b-4042-9124-f1f6d7a444f9" />
